config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  get 'about', to: "home#about", as: :about

  resources :help_centers do
    collection do
      get 'search'
      get 'donate'
    end
    member do
      get 'donate'
    end
  end

  resources :volunteers do

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/help_center.rb
class HelpCenter < ApplicationRecord
  CenterTypes = {
    'Immigration': ImmigrationHelpCenter
  }

end

app/models/immigration_help_center.rb
class ImmigrationHelpCenter < HelpCenter

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  SPECIALITY = [
    "Community Organizer",
    "Designer",
    "Doctor",
    "Lawyer",
    "Marketing",
    "Software Engineer",
    "Student",
    "Supporter",
    "Teacher",
    "Other",
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/get_help_controller.rb
class GetHelpController < ApplicationController
end

app/controllers/help_centers_controller.rb
class HelpCentersController < ApplicationController
  def donate
    donate_url = HelpCenter.find(params[:id]).donate_url
    redirect_to donate_url if donate_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @help_center = HelpCenter.new
    @volunteer = Volunteer.new
  end

  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/volunteer_controller.rb
class VolunteerController < ApplicationController
  def create

  end

  def search
    render text => "Still building"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_help_helper.rb
module GetHelpHelper
end

app/helpers/help_centers_helper.rb
module HelpCentersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/home/_contact.erb
<style>
 .btn-link-fix {
     padding: 0px 20px 0 20px !important
 }
</style>
<!-- About us -->
<div class="contact-container section-container section-container-gray-bg" id="contact">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 about-us section-description wow fadeIn">
        <h2><strong>Get</strong> updates</h2>
        <div class="divider-1 wow fadeInUp"><span></span></div>
        <h3>We are building up CloudCost. Keep informed.</h3>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 about-us-box wow fadeInDown">
        <div id="mc_embed_signup">
          <form action="//acksin.us13.list-manage.com/subscribe/post?u=9119109a1ec44da0a7b392f83&amp;id=49e277272a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
              <div class="mc-field-group">
                <input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL" placeholder="Your email">
                <br>
                <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-link-1 btn-link-fix btn-lg">
              </div>
              <div id="mce-responses" class="clear">
                <div class="response" id="mce-error-response" style="display:none"></div>
                <div class="response" id="mce-success-response" style="display:none"></div>
              </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
              <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_9119109a1ec44da0a7b392f83_49e277272a" tabindex="-1" value=""></div>
              <div class="clear"></div>
            </div>
          </form>
        </div>
        <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
        <!--End mc_embed_signup-->

      </div>
    </div>
  </div>
</div>

app/views/home/_features.erb
<!-- Features -->
<div class="features-container section-container" id="features">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 features section-description wow fadeIn">
        <h2>The Left Stands for <b>Courage</b></h2>
        <div class="divider-1 wow fadeInUp"><span></span></div>
      </div>
    </div>
    <div class="row text-left">
      <div class="col-sm-8 col-sm-push-2 lead">
        <p>The Left Stands for Courage. We may not care about every
        issue, but we want each individual to have dominion over
        themselves so that they may lead a better life for themselves
        and their family whatever race, ethnicity, gender, or sexual
        orientation they are. We want our world to be left better even
        if it means sacrificing in the moment. We fight for what is
        right and what is good. We build things and dream far. We may
        get derided and called elitists but we move the world
        forward. The Left dreams Big. We seek progress. We care about
        the aspiration of every individual. We want every individual
        to have dignity and to make a mark.</p>

        <p>We messed up, and we worst off for it. So let's make sure
          the policies of the Left stay intact and that we can help
          secure those values. We have to mobilize the Left. We have
          to find strategies to bring every individual to help. We
          need every person on the Left to tackle issues. We have to
          accept that not every issue we hold is going to be dear to
          everyone. We have to win one person, one issue at a time.</p>

        <p>Let's Get to Work.</p>

      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 section-bottom-button wow fadeInUp">
      </div>
    </div>
  </div>
</div>

app/views/home/_get_help.erb
<div class="features-container section-container" id="features">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 features section-description wow fadeIn">
        <h2>Get Help</h2>
        <div class="divider-1 wow fadeInUp"><span></span></div>
      </div>
    </div>
    <div class="row text-left">
      <div class="col-sm-8 col-sm-push-2 lead">
        If you are in <b>danger</b> or need assistance please use the
        following to find a support center near you.

        <%= form_for @help_center, method: :get  do |f| %>
          <div>
            <%= f.select :type, HelpCenter::CenterTypes.keys, include_blank: true %>
            <%= f.text_field :city, placeholder: "City" %>
            <%= f.text_field :state, placeholder: "State" %>
            <%= f.submit "Get Help", class: "btn btn-success btn-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_our-products.erb
<!-- Call to action -->
<div class="products-container section-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 call-to-action section-description wow fadeInLeftBig">
        <h2><strong></strong>Ideas</h2>

        <div class="divider-1 wow fadeInUp"><span></span></div>
        <div class="col-lg-6 wow fadeInUp">
          <h3>One Issue</h3>
          <p class="text-left">
            Get every person to just focus on one issue that is
            important to them. Have them find out about the laws and
            changes around the country that affect that one issue. We
            need to focus on a platform of people fighting for things
            and issue at a time. One person may care about gay rights
            while another may fight for immigration. But between time
            constraints and other factors we can't have people
            focusing on all issues we should have them focus on
            one. To keep things focused we will only tackle 10 issues
            at a time.
          </p>
        </div>

        <div class="col-lg-6 wow fadeInDown">
          <h3>Localize</h3>

          <p class="text-left">
            We cannot treat Middle America the way we treat Urban
            America. They are two distinct cultures and carry very
            different ideas of how to do things. Middle America
            doesn't like welfare because welfare for them happened
            through the church. Trying to get them to like welfare
            won't work. If we want to bridge the gap of welfare we
            have to incorporate strategies that works well in Middle
            America. One size does not fit all. We have to get the
            individual communities involved. Certain things cannot be
            done through the Church such as Abortion and Gay Rights
            but a lot of other things can get the local community
            involved..
          </p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12 call-to-action section-description wow fadeInLeftBig">
        <div class="col-lg-6 wow fadeInUp">
          <h3>One Issue</h3>
          <p class="text-left">
            Get every person to just focus on one issue that is
            important to them. Have them find out about the laws and
            changes around the country that affect that one issue. We
            need to focus on a platform of people fighting for things
            and issue at a time. One person may care about gay rights
            while another may fight for immigration. But between time
            constraints and other factors we can't have people
            focusing on all issues we should have them focus on
            one. To keep things focused we will only tackle 10 issues
            at a time.
          </p>
        </div>
      </div>
    </div>


    <%#
    <div class="row">
      <div class="col-sm-12 section-bottom-button wow fadeInUp">
        <a class="btn btn-link-1" href="https://blog.acksin.com" target="_blank">Our Blog</a>
        <a class="btn btn-link-2" href="https://devops.acksin.com" target="_blank">Hire Us</a>
      </div>
    </div>
    %>
  </div>
</div>

app/views/home/_quickstart.erb
<!-- More features -->
<div class="quickstart-container section-container section-container-gray-bg" id="quickstart">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 more-features section-description wow fadeIn">
        <h2>Strategies</h2>
        <div class="divider-1 wow fadeInUp"><span></span></div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6 more-features-box wow fadeInLeft text-left">
        <h3>Goals</h3>
        <ul>
          <li>The Left does not have a clear message. Its role is always defined from the right. Let's create a single message.</li>
          <li>The Left fights for many ideas but it is hard for any
          person to mobilize around all of them. By trying to force
          all the issues as equal we are playing a zero-sum game in
          which we lose. We need to take some of the strategies of the
          right and apply them to our issues. We need to fight them at
          an issue by issue level.</li>
          <li>We need to make sure that the Left in Middle America is
          not trampled. We need to help, educate and assist people in
          those communities.</li>
        </ul>
      </div>

      <div class="col-sm-6 more-features-box wow fadeInUp text-left">
        <h3>Platform</h3>
        <ul>
          <li><b>No more niceties.</b> It is time to be aggressive. We
          cannot lose all the progress that we have made.</li>
          <li><b>Evoke Emotion.</b> The message of the Left is
          lackluster. For good or bad the Right has used emotion in
          its fight. We must do the same. We can use facts but humans
          are emotional creatures first. Let's fight with emotion. How
          we sell our ideas matter and for too long the right has
          defined what that message is.</li>
          <li><b>One issue at a time.</b> The goals of the Left are
          large. However, some issues are more pertanent then others
          for different people. We need focus the energies of people
          and win battles one issue at a time.</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/home/_volunteer.erb
<!-- More features -->
<div class="quickstart-container section-container section-container-gray-bg" id="quickstart">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 more-features section-description wow fadeIn">
        <h2>Volunteer</h2>
        <div class="divider-1 wow fadeInUp"><span></span></div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12 more-features section-description wow fadeIn lead">
        <p>
          Help your local Left group whether the Democratic Party,
          helping a local help center or otherwise.
        </p>
        <%= form_for @volunteer do |f| %>
          <%= f.text_field :first_name, placeholder: "First Name" %>
          <br/>
          <%= f.text_field :last_name, placeholder: "Last Name" %>
          <br/>
          <%= f.text_field :email, placeholder: "Email" %>
          <br/>
          <%= f.text_field :phone_number, placeholder: "Phone Number (Optional)" %>
          <br/>
          <%= f.text_field :city, placeholder: "City" %>
          <br/>
          <%= f.text_field :state , placeholder: "State" %>
          <br/>
          Speciality
          <br/>
          <%= f.select :speciality, Volunteer::SPECIALITY %>
          <br/>

          <%= f.submit "Sign Up", class: "btn btn-success btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- Top content -->
<div class="top-content">
  <div class="inner-bg">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text" style="background-color:rgba(0, 0, 0, 0.3); padding-bottom: 1em;">
          <h1 class="wow fadeInLeftBig"><%= "Building the Left, One Person, One Issue and One Vote at a Time" %></h1>
          <div class="description wow fadeInLeftBig">
            <p>
            </p>
          </div>
          <div class="top-big-link wow fadeInUp">
            <a class="btn btn-link-2 scroll-link" href="/#features">Learn more</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: "home/get_help" %>
<%= render partial: "home/volunteer" %>
<%#= render partial: "home/mobilize" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= "BuildLeft" %></title>

    <!-- CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/css/animate.css">
    <link rel="stylesheet" href="/assets/css/form-elements.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/media-queries.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Favicon and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">

    <script src="https://unpkg.com/react@15.3.1/dist/react-with-addons.js"></script>
    <script src="https://unpkg.com/react-dom@15.3.1/dist/react-dom.js"></script>
    <script src="https://unpkg.com/babel-core@5.8.38/browser.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Loader -->
    <div class="loader">
      <div class="loader-img"></div>
    </div>

    <!-- Top menu -->
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-no-bg" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">BuildLeft</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="top-navbar-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Directory", help_centers_path %></li>
            <li><%= link_to "Get Help", search_help_centers_path %></li>
            <li><%= link_to "Volunteer", volunteers_path %></li>
            <li><%= link_to "About", about_path %></li>
          </ul>
        </div>
      </div>
    </nav>

    <main>
      <%= yield %>
    </main>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 footer-social">
            <a href="mailto:abhi@acksin.com"><i class="fa fa-inbox"></i></a>
            <a href="https://github.com/buildleft/buildleft"><i class="fa fa-github"></i></a>
            <a href="https://buildleftslack.herokuapp.com"><i class="fa fa-slack"></i></a>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 footer-copyright">
          </div>
        </div>
      </div>
    </footer>


    <!-- Javascript -->
    <script src="/assets/js/jquery-1.11.1.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.backstretch.min.js"></script>
    <script src="/assets/js/wow.min.js"></script>
    <script src="/assets/js/retina-1.1.0.min.js"></script>
    <script src="/assets/js/waypoints.min.js"></script>
    <script src="/assets/js/scripts.js"></script>

    <!--[if lt IE 10]>
      <script src="/assets/js/placeholder.js"></script>
    <![endif]-->
  </body>
</html>